# Generated by Django 2.2 on 2023-03-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='count_test',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество пройденных тестов'),
        ),
    ]
